---
- name: Konfiguration des Zielsystems
  hosts: ansible_host
  become: yes

  tasks:
    - name: update all packages to the latest versions
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Install apt packages
      apt:
        name: 
          - git
          - docker.io
          - docker-compose
          - nodejs
          - npm          
        state: present

    - name: Install node.js / npm packages
      community.general.npm:
        name:
          - cors@2.8.5
          - express@4.18.2
          - mongoose@8.0.2
        state: present
        global: yes

    - name: Clone the project repository
      git:
        repo: 'git@github.com:lekrieger/todo-app.git'
        dest: /home/leon/todo-app
        clone: yes
        update: yes
      become: no
      become_user: leon

    - name: Copy Index.html to Apache directory
      copy:
        src: /home/leon/todo-app/frontend/index.html
        dest: /var/www/html/index.html

    - name: Configure SSH
      copy:
        src: /home/leon/todo-app/config
        dest: /home/leon/.ssh/config
        owner: leon
        group: leon
        mode: '0644'

    - name: Run `docker-compose up` for the mongodb 
      community.docker.docker_compose:
        project_src: /home/git/todo-app/mongodb

    - name: Create apache container
      community.docker.docker_image:
        build:
          path: /home/git/todo-app
        name: apache_container
        tag: latest

    - name: run apache container
      docker_container:
        name: apache_container
        image: apache
